# step 3
# email the meeting summary to the user via Gmail SMTP (nicely formatted + transcript attached)

import os
import smtplib
from email.message import EmailMessage
from datetime import datetime, timezone

import markdown as md
from dotenv import load_dotenv

load_dotenv()

GMAIL_ADDRESS = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"].replace(" ", "")


# a styled HTML shell so the email looks clean in Gmail/Outlook/etc.
def _build_html(summary_md: str) -> str:
    body = md.markdown(summary_md, extensions=["extra", "sane_lists"])
    today = datetime.now(timezone.utc).strftime("%d %b %Y")
    return f"""\
<div style="background:#f4f4f7;padding:24px 0;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:14px;
              overflow:hidden;box-shadow:0 2px 10px rgba(0,0,0,0.06);">
    <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);padding:26px 30px;color:#fff;">
      <div style="font-size:22px;font-weight:700;">🎙️ Meeting Summary</div>
      <div style="font-size:13px;opacity:.85;margin-top:4px;">Generated by Meeting Reader · {today}</div>
    </div>
    <div style="padding:26px 30px;color:#1f2933;font-size:15px;line-height:1.6;">
      {body}
    </div>
    <div style="padding:16px 30px;background:#fafafa;border-top:1px solid #eee;
                color:#8a94a6;font-size:12px;">
      The full transcript is attached as a text file.
    </div>
  </div>
</div>
"""


# small stylesheet applied to the markdown-generated tags (Gmail supports <style> in body)
_STYLE = """
<style>
  h2 { font-size:16px; color:#4f46e5; margin:22px 0 8px; border-bottom:1px solid #eee; padding-bottom:4px; }
  h3 { font-size:15px; color:#4f46e5; margin:18px 0 6px; }
  ul { margin:6px 0 6px 18px; padding:0; }
  li { margin:4px 0; }
  p  { margin:8px 0; }
</style>
"""


def send_summary_email(to_email: str, summary_md: str, transcript: str | None = None) -> None:
    msg = EmailMessage()
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = to_email
    msg["Subject"] = "Your Meeting Summary"

    # plain-text fallback for email clients that don't render HTML
    msg.set_content(summary_md)
    # rich HTML version
    msg.add_alternative(_STYLE + _build_html(summary_md), subtype="html")

    # attach the full transcript as a .txt file
    if transcript:
        msg.add_attachment(
            transcript.encode("utf-8"),
            maintype="text",
            subtype="plain",
            filename="transcript.txt",
        )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)


if __name__ == "__main__":
    import sys
    demo = "## Summary\nThis is a **test** email.\n\n## Action Items\n- [Shubham] Ship on Friday"
    send_summary_email(sys.argv[1], demo, transcript="Speaker 1: Hello world.")
    print("Sent!")
